package com.bergenproduction.pilltracker.core.ui.designsystem.theme

import androidx.compose.ui.graphics.Color

object ColorPink {
    val primaryLight = Color(0xFF6F528A)
    val onPrimaryLight = Color(0xFFFFFFFF)
    val primaryContainerLight = Color(0xFFF1DBFF)
    val onPrimaryContainerLight = Color(0xFF563A70)
    val secondaryLight = Color(0xFF665A6F)
    val onSecondaryLight = Color(0xFFFFFFFF)
    val secondaryContainerLight = Color(0xFFEDDDF6)
    val onSecondaryContainerLight = Color(0xFF4E4256)
    val tertiaryLight = Color(0xFF805157)
    val onTertiaryLight = Color(0xFFFFFFFF)
    val tertiaryContainerLight = Color(0xFFFFD9DC)
    val onTertiaryContainerLight = Color(0xFF653A40)
    val errorLight = Color(0xFFBA1A1A)
    val onErrorLight = Color(0xFFFFFFFF)
    val errorContainerLight = Color(0xFFFFDAD6)
    val onErrorContainerLight = Color(0xFF93000A)
    val backgroundLight = Color(0xFFFFF7FE)
    val onBackgroundLight = Color(0xFF1E1A20)
    val surfaceLight = Color(0xFFFFF7FE)
    val onSurfaceLight = Color(0xFF1E1A20)
    val surfaceVariantLight = Color(0xFFE9DFEB)
    val onSurfaceVariantLight = Color(0xFF4A454D)
    val outlineLight = Color(0xFF7C757E)
    val outlineVariantLight = Color(0xFFCDC4CE)
    val scrimLight = Color(0xFF000000)
    val inverseSurfaceLight = Color(0xFF332F35)
    val inverseOnSurfaceLight = Color(0xFFF7EEF6)
    val inversePrimaryLight = Color(0xFFDCB9F8)
    val surfaceDimLight = Color(0xFFDFD8DF)
    val surfaceBrightLight = Color(0xFFFFF7FE)
    val surfaceContainerLowestLight = Color(0xFFFFFFFF)
    val surfaceContainerLowLight = Color(0xFFF9F1F9)
    val surfaceContainerLight = Color(0xFFF4EBF3)
    val surfaceContainerHighLight = Color(0xFFEEE6EE)
    val surfaceContainerHighestLight = Color(0xFFE8E0E8)

    val primaryDark = Color(0xFFDCB9F8)
    val onPrimaryDark = Color(0xFF3F2458)
    val primaryContainerDark = Color(0xFF563A70)
    val onPrimaryContainerDark = Color(0xFFF1DBFF)
    val secondaryDark = Color(0xFFD1C1D9)
    val onSecondaryDark = Color(0xFF372C3F)
    val secondaryContainerDark = Color(0xFF4E4256)
    val onSecondaryContainerDark = Color(0xFFEDDDF6)
    val tertiaryDark = Color(0xFFF3B7BD)
    val onTertiaryDark = Color(0xFF4B252A)
    val tertiaryContainerDark = Color(0xFF653A40)
    val onTertiaryContainerDark = Color(0xFFFFD9DC)
    val errorDark = Color(0xFFFFB4AB)
    val onErrorDark = Color(0xFF690005)
    val errorContainerDark = Color(0xFF93000A)
    val onErrorContainerDark = Color(0xFFFFDAD6)
    val backgroundDark = Color(0xFF151217)
    val onBackgroundDark = Color(0xFFE8E0E8)
    val surfaceDark = Color(0xFF151217)
    val onSurfaceDark = Color(0xFFE8E0E8)
    val surfaceVariantDark = Color(0xFF4A454D)
    val onSurfaceVariantDark = Color(0xFFCDC4CE)
    val outlineDark = Color(0xFF968E98)
    val outlineVariantDark = Color(0xFF4A454D)
    val scrimDark = Color(0xFF000000)
    val inverseSurfaceDark = Color(0xFFE8E0E8)
    val inverseOnSurfaceDark = Color(0xFF332F35)
    val inversePrimaryDark = Color(0xFF6F528A)
    val surfaceDimDark = Color(0xFF151217)
    val surfaceBrightDark = Color(0xFF3C383E)
    val surfaceContainerLowestDark = Color(0xFF100D12)
    val surfaceContainerLowDark = Color(0xFF1E1A20)
    val surfaceContainerDark = Color(0xFF221E24)
    val surfaceContainerHighDark = Color(0xFF2C292E)
    val surfaceContainerHighestDark = Color(0xFF373339)
}
