package com.bergenproduction.pilltracker.core.ui.designsystem.theme

import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.runtime.Composable
import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color

private val lightPinkScheme = lightColorScheme(
    primary = ColorPink.primaryLight,
    onPrimary = ColorPink.onPrimaryLight,
    primaryContainer = ColorPink.primaryContainerLight,
    onPrimaryContainer = ColorPink.onPrimaryContainerLight,
    secondary = ColorPink.secondaryLight,
    onSecondary = ColorPink.onSecondaryLight,
    secondaryContainer = ColorPink.secondaryContainerLight,
    onSecondaryContainer = ColorPink.onSecondaryContainerLight,
    tertiary = ColorPink.tertiaryLight,
    onTertiary = ColorPink.onTertiaryLight,
    tertiaryContainer = ColorPink.tertiaryContainerLight,
    onTertiaryContainer = ColorPink.onTertiaryContainerLight,
    error = ColorPink.errorLight,
    onError = ColorPink.onErrorLight,
    errorContainer = ColorPink.errorContainerLight,
    onErrorContainer = ColorPink.onErrorContainerLight,
    background = ColorPink.backgroundLight,
    onBackground = ColorPink.onBackgroundLight,
    surface = ColorPink.surfaceLight,
    onSurface = ColorPink.onSurfaceLight,
    surfaceVariant = ColorPink.surfaceVariantLight,
    onSurfaceVariant = ColorPink.onSurfaceVariantLight,
    outline = ColorPink.outlineLight,
    outlineVariant = ColorPink.outlineVariantLight,
    scrim = ColorPink.scrimLight,
    inverseSurface = ColorPink.inverseSurfaceLight,
    inverseOnSurface = ColorPink.inverseOnSurfaceLight,
    inversePrimary = ColorPink.inversePrimaryLight,
    surfaceDim = ColorPink.surfaceDimLight,
    surfaceBright = ColorPink.surfaceBrightLight,
    surfaceContainerLowest = ColorPink.surfaceContainerLowestLight,
    surfaceContainerLow = ColorPink.surfaceContainerLowLight,
    surfaceContainer = ColorPink.surfaceContainerLight,
    surfaceContainerHigh = ColorPink.surfaceContainerHighLight,
    surfaceContainerHighest = ColorPink.surfaceContainerHighestLight,
)

private val darkPinkScheme = darkColorScheme(
    primary = ColorPink.primaryDark,
    onPrimary = ColorPink.onPrimaryDark,
    primaryContainer = ColorPink.primaryContainerDark,
    onPrimaryContainer = ColorPink.onPrimaryContainerDark,
    secondary = ColorPink.secondaryDark,
    onSecondary = ColorPink.onSecondaryDark,
    secondaryContainer = ColorPink.secondaryContainerDark,
    onSecondaryContainer = ColorPink.onSecondaryContainerDark,
    tertiary = ColorPink.tertiaryDark,
    onTertiary = ColorPink.onTertiaryDark,
    tertiaryContainer = ColorPink.tertiaryContainerDark,
    onTertiaryContainer = ColorPink.onTertiaryContainerDark,
    error = ColorPink.errorDark,
    onError = ColorPink.onErrorDark,
    errorContainer = ColorPink.errorContainerDark,
    onErrorContainer = ColorPink.onErrorContainerDark,
    background = ColorPink.backgroundDark,
    onBackground = ColorPink.onBackgroundDark,
    surface = ColorPink.surfaceDark,
    onSurface = ColorPink.onSurfaceDark,
    surfaceVariant = ColorPink.surfaceVariantDark,
    onSurfaceVariant = ColorPink.onSurfaceVariantDark,
    outline = ColorPink.outlineDark,
    outlineVariant = ColorPink.outlineVariantDark,
    scrim = ColorPink.scrimDark,
    inverseSurface = ColorPink.inverseSurfaceDark,
    inverseOnSurface = ColorPink.inverseOnSurfaceDark,
    inversePrimary = ColorPink.inversePrimaryDark,
    surfaceDim = ColorPink.surfaceDimDark,
    surfaceBright = ColorPink.surfaceBrightDark,
    surfaceContainerLowest = ColorPink.surfaceContainerLowestDark,
    surfaceContainerLow = ColorPink.surfaceContainerLowDark,
    surfaceContainer = ColorPink.surfaceContainerDark,
    surfaceContainerHigh = ColorPink.surfaceContainerHighDark,
    surfaceContainerHighest = ColorPink.surfaceContainerHighestDark,
)
private val lightRedScheme = lightColorScheme(
    primary = ColorRed.primaryLight,
    onPrimary = ColorRed.onPrimaryLight,
    primaryContainer = ColorRed.primaryContainerLight,
    onPrimaryContainer = ColorRed.onPrimaryContainerLight,
    secondary = ColorRed.secondaryLight,
    onSecondary = ColorRed.onSecondaryLight,
    secondaryContainer = ColorRed.secondaryContainerLight,
    onSecondaryContainer = ColorRed.onSecondaryContainerLight,
    tertiary = ColorRed.tertiaryLight,
    onTertiary = ColorRed.onTertiaryLight,
    tertiaryContainer = ColorRed.tertiaryContainerLight,
    onTertiaryContainer = ColorRed.onTertiaryContainerLight,
    error = ColorRed.errorLight,
    onError = ColorRed.onErrorLight,
    errorContainer = ColorRed.errorContainerLight,
    onErrorContainer = ColorRed.onErrorContainerLight,
    background = ColorRed.backgroundLight,
    onBackground = ColorRed.onBackgroundLight,
    surface = ColorRed.surfaceLight,
    onSurface = ColorRed.onSurfaceLight,
    surfaceVariant = ColorRed.surfaceVariantLight,
    onSurfaceVariant = ColorRed.onSurfaceVariantLight,
    outline = ColorRed.outlineLight,
    outlineVariant = ColorRed.outlineVariantLight,
    scrim = ColorRed.scrimLight,
    inverseSurface = ColorRed.inverseSurfaceLight,
    inverseOnSurface = ColorRed.inverseOnSurfaceLight,
    inversePrimary = ColorRed.inversePrimaryLight,
    surfaceDim = ColorRed.surfaceDimLight,
    surfaceBright = ColorRed.surfaceBrightLight,
    surfaceContainerLowest = ColorRed.surfaceContainerLowestLight,
    surfaceContainerLow = ColorRed.surfaceContainerLowLight,
    surfaceContainer = ColorRed.surfaceContainerLight,
    surfaceContainerHigh = ColorRed.surfaceContainerHighLight,
    surfaceContainerHighest = ColorRed.surfaceContainerHighestLight,
)

private val darkRedScheme = darkColorScheme(
    primary = ColorRed.primaryDark,
    onPrimary = ColorRed.onPrimaryDark,
    primaryContainer = ColorRed.primaryContainerDark,
    onPrimaryContainer = ColorRed.onPrimaryContainerDark,
    secondary = ColorRed.secondaryDark,
    onSecondary = ColorRed.onSecondaryDark,
    secondaryContainer = ColorRed.secondaryContainerDark,
    onSecondaryContainer = ColorRed.onSecondaryContainerDark,
    tertiary = ColorRed.tertiaryDark,
    onTertiary = ColorRed.onTertiaryDark,
    tertiaryContainer = ColorRed.tertiaryContainerDark,
    onTertiaryContainer = ColorRed.onTertiaryContainerDark,
    error = ColorRed.errorDark,
    onError = ColorRed.onErrorDark,
    errorContainer = ColorRed.errorContainerDark,
    onErrorContainer = ColorRed.onErrorContainerDark,
    background = ColorRed.backgroundDark,
    onBackground = ColorRed.onBackgroundDark,
    surface = ColorRed.surfaceDark,
    onSurface = ColorRed.onSurfaceDark,
    surfaceVariant = ColorRed.surfaceVariantDark,
    onSurfaceVariant = ColorRed.onSurfaceVariantDark,
    outline = ColorRed.outlineDark,
    outlineVariant = ColorRed.outlineVariantDark,
    scrim = ColorRed.scrimDark,
    inverseSurface = ColorRed.inverseSurfaceDark,
    inverseOnSurface = ColorRed.inverseOnSurfaceDark,
    inversePrimary = ColorRed.inversePrimaryDark,
    surfaceDim = ColorRed.surfaceDimDark,
    surfaceBright = ColorRed.surfaceBrightDark,
    surfaceContainerLowest = ColorRed.surfaceContainerLowestDark,
    surfaceContainerLow = ColorRed.surfaceContainerLowDark,
    surfaceContainer = ColorRed.surfaceContainerDark,
    surfaceContainerHigh = ColorRed.surfaceContainerHighDark,
    surfaceContainerHighest = ColorRed.surfaceContainerHighestDark,
)
private val lightBlueScheme = lightColorScheme(
    primary = ColorBlue.primaryLight,
    onPrimary = ColorBlue.onPrimaryLight,
    primaryContainer = ColorBlue.primaryContainerLight,
    onPrimaryContainer = ColorBlue.onPrimaryContainerLight,
    secondary = ColorBlue.secondaryLight,
    onSecondary = ColorBlue.onSecondaryLight,
    secondaryContainer = ColorBlue.secondaryContainerLight,
    onSecondaryContainer = ColorBlue.onSecondaryContainerLight,
    tertiary = ColorBlue.tertiaryLight,
    onTertiary = ColorBlue.onTertiaryLight,
    tertiaryContainer = ColorBlue.tertiaryContainerLight,
    onTertiaryContainer = ColorBlue.onTertiaryContainerLight,
    error = ColorBlue.errorLight,
    onError = ColorBlue.onErrorLight,
    errorContainer = ColorBlue.errorContainerLight,
    onErrorContainer = ColorBlue.onErrorContainerLight,
    background = ColorBlue.backgroundLight,
    onBackground = ColorBlue.onBackgroundLight,
    surface = ColorBlue.surfaceLight,
    onSurface = ColorBlue.onSurfaceLight,
    surfaceVariant = ColorBlue.surfaceVariantLight,
    onSurfaceVariant = ColorBlue.onSurfaceVariantLight,
    outline = ColorBlue.outlineLight,
    outlineVariant = ColorBlue.outlineVariantLight,
    scrim = ColorBlue.scrimLight,
    inverseSurface = ColorBlue.inverseSurfaceLight,
    inverseOnSurface = ColorBlue.inverseOnSurfaceLight,
    inversePrimary = ColorBlue.inversePrimaryLight,
    surfaceDim = ColorBlue.surfaceDimLight,
    surfaceBright = ColorBlue.surfaceBrightLight,
    surfaceContainerLowest = ColorBlue.surfaceContainerLowestLight,
    surfaceContainerLow = ColorBlue.surfaceContainerLowLight,
    surfaceContainer = ColorBlue.surfaceContainerLight,
    surfaceContainerHigh = ColorBlue.surfaceContainerHighLight,
    surfaceContainerHighest = ColorBlue.surfaceContainerHighestLight,
)

private val darkBlueScheme = darkColorScheme(
    primary = ColorBlue.primaryDark,
    onPrimary = ColorBlue.onPrimaryDark,
    primaryContainer = ColorBlue.primaryContainerDark,
    onPrimaryContainer = ColorBlue.onPrimaryContainerDark,
    secondary = ColorBlue.secondaryDark,
    onSecondary = ColorBlue.onSecondaryDark,
    secondaryContainer = ColorBlue.secondaryContainerDark,
    onSecondaryContainer = ColorBlue.onSecondaryContainerDark,
    tertiary = ColorBlue.tertiaryDark,
    onTertiary = ColorBlue.onTertiaryDark,
    tertiaryContainer = ColorBlue.tertiaryContainerDark,
    onTertiaryContainer = ColorBlue.onTertiaryContainerDark,
    error = ColorBlue.errorDark,
    onError = ColorBlue.onErrorDark,
    errorContainer = ColorBlue.errorContainerDark,
    onErrorContainer = ColorBlue.onErrorContainerDark,
    background = ColorBlue.backgroundDark,
    onBackground = ColorBlue.onBackgroundDark,
    surface = ColorBlue.surfaceDark,
    onSurface = ColorBlue.onSurfaceDark,
    surfaceVariant = ColorBlue.surfaceVariantDark,
    onSurfaceVariant = ColorBlue.onSurfaceVariantDark,
    outline = ColorBlue.outlineDark,
    outlineVariant = ColorBlue.outlineVariantDark,
    scrim = ColorBlue.scrimDark,
    inverseSurface = ColorBlue.inverseSurfaceDark,
    inverseOnSurface = ColorBlue.inverseOnSurfaceDark,
    inversePrimary = ColorBlue.inversePrimaryDark,
    surfaceDim = ColorBlue.surfaceDimDark,
    surfaceBright = ColorBlue.surfaceBrightDark,
    surfaceContainerLowest = ColorBlue.surfaceContainerLowestDark,
    surfaceContainerLow = ColorBlue.surfaceContainerLowDark,
    surfaceContainer = ColorBlue.surfaceContainerDark,
    surfaceContainerHigh = ColorBlue.surfaceContainerHighDark,
    surfaceContainerHighest = ColorBlue.surfaceContainerHighestDark,
)

private val lightGreenScheme = lightColorScheme(
    primary = ColorGreen.primaryLight,
    onPrimary = ColorGreen.onPrimaryLight,
    primaryContainer = ColorGreen.primaryContainerLight,
    onPrimaryContainer = ColorGreen.onPrimaryContainerLight,
    secondary = ColorGreen.secondaryLight,
    onSecondary = ColorGreen.onSecondaryLight,
    secondaryContainer = ColorGreen.secondaryContainerLight,
    onSecondaryContainer = ColorGreen.onSecondaryContainerLight,
    tertiary = ColorGreen.tertiaryLight,
    onTertiary = ColorGreen.onTertiaryLight,
    tertiaryContainer = ColorGreen.tertiaryContainerLight,
    onTertiaryContainer = ColorGreen.onTertiaryContainerLight,
    error = ColorGreen.errorLight,
    onError = ColorGreen.onErrorLight,
    errorContainer = ColorGreen.errorContainerLight,
    onErrorContainer = ColorGreen.onErrorContainerLight,
    background = ColorGreen.backgroundLight,
    onBackground = ColorGreen.onBackgroundLight,
    surface = ColorGreen.surfaceLight,
    onSurface = ColorGreen.onSurfaceLight,
    surfaceVariant = ColorGreen.surfaceVariantLight,
    onSurfaceVariant = ColorGreen.onSurfaceVariantLight,
    outline = ColorGreen.outlineLight,
    outlineVariant = ColorGreen.outlineVariantLight,
    scrim = ColorGreen.scrimLight,
    inverseSurface = ColorGreen.inverseSurfaceLight,
    inverseOnSurface = ColorGreen.inverseOnSurfaceLight,
    inversePrimary = ColorGreen.inversePrimaryLight,
    surfaceDim = ColorGreen.surfaceDimLight,
    surfaceBright = ColorGreen.surfaceBrightLight,
    surfaceContainerLowest = ColorGreen.surfaceContainerLowestLight,
    surfaceContainerLow = ColorGreen.surfaceContainerLowLight,
    surfaceContainer = ColorGreen.surfaceContainerLight,
    surfaceContainerHigh = ColorGreen.surfaceContainerHighLight,
    surfaceContainerHighest = ColorGreen.surfaceContainerHighestLight,
)

private val darkGreenScheme = darkColorScheme(
    primary = ColorGreen.primaryDark,
    onPrimary = ColorGreen.onPrimaryDark,
    primaryContainer = ColorGreen.primaryContainerDark,
    onPrimaryContainer = ColorGreen.onPrimaryContainerDark,
    secondary = ColorGreen.secondaryDark,
    onSecondary = ColorGreen.onSecondaryDark,
    secondaryContainer = ColorGreen.secondaryContainerDark,
    onSecondaryContainer = ColorGreen.onSecondaryContainerDark,
    tertiary = ColorGreen.tertiaryDark,
    onTertiary = ColorGreen.onTertiaryDark,
    tertiaryContainer = ColorGreen.tertiaryContainerDark,
    onTertiaryContainer = ColorGreen.onTertiaryContainerDark,
    error = ColorGreen.errorDark,
    onError = ColorGreen.onErrorDark,
    errorContainer = ColorGreen.errorContainerDark,
    onErrorContainer = ColorGreen.onErrorContainerDark,
    background = ColorGreen.backgroundDark,
    onBackground = ColorGreen.onBackgroundDark,
    surface = ColorGreen.surfaceDark,
    onSurface = ColorGreen.onSurfaceDark,
    surfaceVariant = ColorGreen.surfaceVariantDark,
    onSurfaceVariant = ColorGreen.onSurfaceVariantDark,
    outline = ColorGreen.outlineDark,
    outlineVariant = ColorGreen.outlineVariantDark,
    scrim = ColorGreen.scrimDark,
    inverseSurface = ColorGreen.inverseSurfaceDark,
    inverseOnSurface = ColorGreen.inverseOnSurfaceDark,
    inversePrimary = ColorGreen.inversePrimaryDark,
    surfaceDim = ColorGreen.surfaceDimDark,
    surfaceBright = ColorGreen.surfaceBrightDark,
    surfaceContainerLowest = ColorGreen.surfaceContainerLowestDark,
    surfaceContainerLow = ColorGreen.surfaceContainerLowDark,
    surfaceContainer = ColorGreen.surfaceContainerDark,
    surfaceContainerHigh = ColorGreen.surfaceContainerHighDark,
    surfaceContainerHighest = ColorGreen.surfaceContainerHighestDark,
)

@Immutable
data class ColorFamily(
    val color: Color,
    val onColor: Color,
    val colorContainer: Color,
    val onColorContainer: Color
)

val unspecified_scheme = ColorFamily(
    Color.Unspecified, Color.Unspecified, Color.Unspecified, Color.Unspecified
)

enum class AppThemeColorScheme {
    GREEN, RED, BLUE, PINK
}

@Composable
fun PillTrackerTheme(
    theme: AppThemeColorScheme = AppThemeColorScheme.GREEN,
    darkTheme: Boolean = isSystemInDarkTheme(),
    // Dynamic color is available on Android 12+
    content: @Composable() () -> Unit
) {
    val colorScheme = when (theme) {
        AppThemeColorScheme.GREEN -> if (darkTheme) darkGreenScheme else lightGreenScheme
        AppThemeColorScheme.RED -> if (darkTheme) darkRedScheme else lightRedScheme
        AppThemeColorScheme.BLUE -> if (darkTheme) darkBlueScheme else lightBlueScheme
        AppThemeColorScheme.PINK -> if (darkTheme) darkPinkScheme else lightPinkScheme
    }

    MaterialTheme(
        colorScheme = colorScheme,
        typography = AppTypography,
        content = content
    )
}

